fragment CharacterFields on Character {
  name
  image
  status
  species
  type
  gender
  origin {
    name
  }
}

query GetCharacters($filter: FilterCharacter, $page: Int) {
  characters(filter: $filter, page: $page) {
    info {
      count
      pages
    }
    results {
      id
      ...CharacterFields
    }
  }
}

query GetCharacter($id: ID!) {
  character(id: $id) {
    ...CharacterFields
  }
}
